/**
 * @file    sdio_diskio.c
 * @brief   FatFS disk I/O driver for SDIO (4-bit) on STM32F405
 *
 * WeAct STM32F405RGT6 onboard TF slot — SDIO peripheral pins
 * (read directly from schematic, TF interface section, row D):
 *
 *   PC8  = SDIO_D0   (DAT0)   AF12
 *   PC9  = SDIO_D1   (DAT1)   AF12
 *   PC10 = SDIO_D2   (DAT2)   AF12
 *   PC11 = SDIO_D3   (DAT3)   AF12
 *   PC12 = SDIO_CK   (CLK)    AF12
 *   PD2  = SDIO_CMD  (CMD)    AF12
 *
 * DMA assignments (fixed by STM32F4 DMA mux):
 *   SDIO RX  →  DMA2 Stream 3, Channel 4
 *   SDIO TX  →  DMA2 Stream 6, Channel 4
 *
 * This implements the five FatFS diskio callbacks.
 * HAL SD handle (hsd) must be generated by CubeMX → Connectivity → SDIO.
 *
 * FatFS ffconf.h must have:
 *   FF_MIN_SS = FF_MAX_SS = 512
 *   FF_FS_READONLY  = 0
 *   FF_USE_MKFS     = 1
 */

#include "sdio_diskio.h"
#include "debug_uart.h"
#include "stm32f4xx_hal.h"
#include "ff_gen_drv.h"

extern SD_HandleTypeDef hsd;

static volatile uint8_t s_rx_cplt   = 0;
static volatile uint8_t s_tx_cplt   = 0;
static volatile uint8_t s_dma_error = 0;

#define SDIO_TIMEOUT_MS   5000u
#define SDIO_BLOCK_SIZE   512u

static volatile DSTATUS s_stat = STA_NOINIT;

DSTATUS SD_disk_initialize(BYTE pdrv)
{
    (void)pdrv;

    /* hsd already initialized by MX_SDIO_SD_Init() in main.c.
     * Just verify the card is in transfer state and mark ready. */
    uint32_t t0 = HAL_GetTick();
    while (HAL_SD_GetCardState(&hsd) != HAL_SD_CARD_TRANSFER) {
        if ((HAL_GetTick() - t0) > 1000u) {
            DBG_Printf("[SDIO] Card not ready at disk_initialize\r\n");
            s_stat = STA_NOINIT;
            return s_stat;
        }
    }

    if (HAL_SD_ConfigWideBusOperation(&hsd, SDIO_BUS_WIDE_4B) != HAL_OK) {
        DBG_Printf("[SDIO] 4-bit bus config failed, using 1-bit\r\n");
    } else {
        DBG_Printf("[SDIO] 4-bit bus configured\r\n");
    }

    s_stat = 0;
    DBG_Printf("[SDIO] Init OK — CardType=%lu BlockNbr=%lu BlockSize=%lu\r\n",
               (unsigned long)hsd.SdCard.CardType,
               (unsigned long)hsd.SdCard.LogBlockNbr,
               (unsigned long)hsd.SdCard.LogBlockSize);
    return s_stat;
}

DSTATUS SD_disk_status(BYTE pdrv)
{
    (void)pdrv;
    return s_stat;
}

DRESULT SD_disk_read(BYTE pdrv,
                     BYTE *buff,
                     DWORD sector,
                     UINT count)
{
    (void)pdrv;

    if (s_stat & STA_NOINIT)
        return RES_NOTRDY;

    if (!count)
        return RES_PARERR;

    DBG_Printf("[SDIO] Read sector=%lu count=%u\r\n",
               (unsigned long)sector,
               count);

    if (HAL_SD_ReadBlocks(
            &hsd,
            buff,
            sector,
            count,
            SDIO_TIMEOUT_MS
        ) != HAL_OK)
    {
        DBG_Printf("[SDIO] Read FAILED err=0x%08lX\r\n",
                   (unsigned long)HAL_SD_GetError(&hsd));
        return RES_ERROR;
    }

    return RES_OK;
}
DRESULT SD_disk_write(BYTE pdrv,
                      const BYTE *buff,
                      DWORD sector,
                      UINT count)
{
    (void)pdrv;

    if (s_stat & STA_NOINIT)
        return RES_NOTRDY;

    if (!count)
        return RES_PARERR;

    DBG_Printf("[SDIO] Write sector=%lu count=%u\r\n",
               (unsigned long)sector,
               count);

    if (HAL_SD_WriteBlocks(
            &hsd,
            (uint8_t *)buff,
            sector,
            count,
            SDIO_TIMEOUT_MS
        ) != HAL_OK)
    {
        DBG_Printf("[SDIO] Write FAILED err=0x%08lX\r\n",
                   (unsigned long)HAL_SD_GetError(&hsd));
        return RES_ERROR;
    }

    return RES_OK;
}

DRESULT SD_disk_ioctl(BYTE pdrv, BYTE cmd, void *buff)
{
    (void)pdrv;

    if (s_stat & STA_NOINIT) return RES_NOTRDY;

    HAL_SD_CardInfoTypeDef info;

    switch (cmd) {
        case CTRL_SYNC:
            {
                uint32_t t0 = HAL_GetTick();
                while (HAL_SD_GetCardState(&hsd) != HAL_SD_CARD_TRANSFER) {
                    if ((HAL_GetTick() - t0) > SDIO_TIMEOUT_MS) return RES_ERROR;
                }
            }
            return RES_OK;

        case GET_SECTOR_COUNT:
            HAL_SD_GetCardInfo(&hsd, &info);
            *(DWORD *)buff = (DWORD)info.LogBlockNbr;
            return RES_OK;

        case GET_SECTOR_SIZE:
            *(WORD *)buff = (WORD)SDIO_BLOCK_SIZE;
            return RES_OK;

        case GET_BLOCK_SIZE:
            HAL_SD_GetCardInfo(&hsd, &info);
            *(DWORD *)buff = info.LogBlockSize / SDIO_BLOCK_SIZE;
            return RES_OK;

        case CTRL_TRIM:
            return RES_OK;

        default:
            return RES_PARERR;
    }
}

/* 
   HAL SD DMA Transfer Completion Callbacks
   These are called from DMA2_Stream3_IRQHandler (RX) and
   DMA2_Stream6_IRQHandler (TX) via HAL_DMA_IRQHandler() in stm32f4xx_it.c
    */

void HAL_SD_RxCpltCallback(SD_HandleTypeDef *hsd_p)
{
    (void)hsd_p;
    s_rx_cplt = 1;
}

void HAL_SD_TxCpltCallback(SD_HandleTypeDef *hsd_p)
{
    (void)hsd_p;
    s_tx_cplt = 1;
}

void HAL_SD_ErrorCallback(SD_HandleTypeDef *hsd_p)
{
    (void)hsd_p;
    s_dma_error = 1;
    DBG_Printf("[SDIO] HAL_SD_ErrorCallback!\r\n");
}

const Diskio_drvTypeDef SD_Driver = {
    SD_disk_initialize,
    SD_disk_status,
    SD_disk_read,
    SD_disk_write,
    SD_disk_ioctl,
};
