/**
 * @file    sdio_diskio.h
 * @brief   FatFS diskio callbacks for SDIO 4-bit on STM32F405
 *
 * Register with FatFS by calling:
 *   FATFS_LinkDriver(&SD_Driver, SDPath);
 * in MX_FATFS_Init() (fatfs.c, generated by CubeMX).
 *
 * Pin mapping (WeAct STM32F405RGT6 onboard TF slot):
 *   PC8  SDIO_D0   PC9  SDIO_D1   PC10 SDIO_D2
 *   PC11 SDIO_D3   PC12 SDIO_CK   PD2  SDIO_CMD
 *   All AF12.
 *
 * DMA2 Stream3 Ch4 = SDIO_RX
 * DMA2 Stream6 Ch4 = SDIO_TX
 */

#ifndef SDIO_DISKIO_H
#define SDIO_DISKIO_H

#include "ff.h"
#include "diskio.h"
#include "ff_gen_drv.h"
    
#ifdef __cplusplus
extern "C" {
#endif

DSTATUS SD_disk_initialize(BYTE pdrv);
DSTATUS SD_disk_status    (BYTE pdrv);
DRESULT SD_disk_read      (BYTE pdrv, BYTE *buff, DWORD sector, UINT count);
DRESULT SD_disk_write     (BYTE pdrv, const BYTE *buff, DWORD sector, UINT count);
DRESULT SD_disk_ioctl     (BYTE pdrv, BYTE cmd, void *buff);

extern const Diskio_drvTypeDef SD_Driver;

#ifdef __cplusplus
}
#endif

#endif /* SDIO_DISKIO_H */
